import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PAGE_SEO } from './data/seo';

/**
 * Regression guard for share-card coverage (task "Catch a new page that
 * ships without its own share card").
 *
 * Share cards in public/images/og/ are generated by
 * scripts/generate-og-cards.mjs from its CARDS map. When a new page is added
 * to PAGE_SEO with an ogImage under /images/og/, three things must hold or
 * the page shares with a broken/missing image:
 *   1. the referenced .jpg exists in public/images/og/
 *   2. the script's CARDS map has an entry for it (so it can be regenerated)
 *   3. (inverse) every CARDS entry / generated file is still referenced,
 *      so stale cards don't linger unnoticed.
 */

const artifactRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ogDir = path.join(artifactRoot, 'public', 'images', 'og');
const scriptPath = path.join(artifactRoot, 'scripts', 'generate-og-cards.mjs');
const imagesSrcDir = path.join(artifactRoot, 'images-src');

// Page names referenced by PAGE_SEO ogImages under /images/og/, e.g. "home".
const referencedPages = new Map<string, string>(); // card name -> PAGE_SEO path
for (const [pagePath, seo] of Object.entries(PAGE_SEO)) {
  const m = seo.ogImage?.match(/\/images\/og\/([^/?]+)\.jpg(?:\?v=\d+)?$/);
  if (m) referencedPages.set(m[1], pagePath);
}

// Top-level keys of the CARDS map in generate-og-cards.mjs. Keys sit at
// two-space indentation inside `const CARDS = { ... };`.
const scriptSource = readFileSync(scriptPath, 'utf8');
const cardsBlock = scriptSource.match(/const CARDS = \{([\s\S]*?)\n\};/)?.[1] ?? '';
const cardKeys = new Set(
  [...cardsBlock.matchAll(/^ {2}(?:'([^']+)'|"([^"]+)"|([\w-]+)):\s*\{/gm)].map(
    (m) => m[1] ?? m[2] ?? m[3],
  ),
);

// card name -> src photo filename, parsed per-entry from the CARDS block.
const cardSources = new Map<string, string>();
for (const entry of cardsBlock.matchAll(
  /^ {2}(?:'([^']+)'|"([^"]+)"|([\w-]+)):\s*\{([\s\S]*?)^ {2}\}/gm,
)) {
  const name = entry[1] ?? entry[2] ?? entry[3];
  const src = entry[4].match(/src:\s*(?:'([^']+)'|"([^"]+)")/);
  if (src) cardSources.set(name, src[1] ?? src[2]);
}

describe('OG share-card coverage', () => {
  it('found PAGE_SEO og references and CARDS entries to compare', () => {
    expect(referencedPages.size).toBeGreaterThan(0);
    expect(cardKeys.size).toBeGreaterThan(0);
  });

  it('every PAGE_SEO ogImage under /images/og/ has a generated file in public/images/og/', () => {
    const missing = [...referencedPages]
      .filter(([card]) => !existsSync(path.join(ogDir, `${card}.jpg`)))
      .map(([card, pagePath]) => `${pagePath} -> /images/og/${card}.jpg`);
    expect(
      missing,
      `Pages reference share cards that do not exist in public/images/og/:\n  ${missing.join(
        '\n  ',
      )}\nAdd an entry to CARDS in scripts/generate-og-cards.mjs and run:\n  node scripts/generate-og-cards.mjs ${missing
        .map((m) => m.match(/og\/(.+)\.jpg/)?.[1])
        .join(' ')}`,
    ).toEqual([]);
  });

  it('every PAGE_SEO ogImage under /images/og/ has a CARDS entry in generate-og-cards.mjs', () => {
    const missing = [...referencedPages]
      .filter(([card]) => !cardKeys.has(card))
      .map(([card, pagePath]) => `${pagePath} -> ${card}`);
    expect(
      missing,
      `Pages use a share card with no CARDS entry in scripts/generate-og-cards.mjs (the card cannot be regenerated):\n  ${missing.join(
        '\n  ',
      )}`,
    ).toEqual([]);
  });

  it('every CARDS entry has a parseable src photo filename', () => {
    const missing = [...cardKeys].filter((card) => !cardSources.has(card));
    expect(
      missing,
      `CARDS entries in scripts/generate-og-cards.mjs have no parseable src: filename:\n  ${missing.join(
        '\n  ',
      )}`,
    ).toEqual([]);
  });

  it("every CARDS src photo exists in images-src/ (regeneration won't break)", () => {
    const missing = [...cardSources]
      .filter(([, src]) => !existsSync(path.join(imagesSrcDir, src)))
      .map(([card, src]) => `${card} -> images-src/${src}`);
    expect(
      missing,
      `CARDS entries in scripts/generate-og-cards.mjs point at source photos missing from images-src/ (regenerating these cards will fail):\n  ${missing.join(
        '\n  ',
      )}\nRestore the photo or update the card's src.`,
    ).toEqual([]);
  });

  it('every CARDS entry is still referenced by a PAGE_SEO ogImage', () => {
    const stale = [...cardKeys].filter((card) => !referencedPages.has(card));
    expect(
      stale,
      `CARDS entries in scripts/generate-og-cards.mjs are no longer referenced by any PAGE_SEO ogImage:\n  ${stale.join(
        '\n  ',
      )}`,
    ).toEqual([]);
  });
});
