// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sightmap-placement/Collapsed.tsx": () => import("../components/mockups/sightmap-placement/Collapsed.tsx"),
  "./components/mockups/sightmap-placement/Expanded.tsx": () => import("../components/mockups/sightmap-placement/Expanded.tsx")
};
