// Build-tool: convert public/images JPEGs to WebP with responsive width
// variants, and emit src/data/imageManifest.ts (dimensions + variant list)
// consumed by <SmartImg>. Floor-plan sheets are already WebP and are skipped.
//
// Idempotent: re-running only regenerates missing/outdated outputs.
// Usage: node scripts/optimize-images.mjs
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';

const run = promisify(execFile);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const imagesDir = path.join(root, 'public', 'images');
const manifestPath = path.join(root, 'src', 'data', 'imageManifest.ts');

const QUALITY = '78';
// Per-stem WebP quality overrides for unusually detail-heavy photos whose
// variants blow past the ~300KB peer norm at the default quality. Slightly
// lower quality is visually indistinguishable but cuts page weight sharply.
const QUALITY_OVERRIDES = {
  'image-077-20170808-0721-c60hfw': '68',
  'image-059-20170808-0852-sw1ncm': '70',
  'image-055-dji-20230620092832-0149-d-yrh5eg': '70',
  'image-058-20170808-0843-ymrdpp': '70',
  'image-056-20170808-0721-c60hfw': '70',
  'image-054-20170808-0677-qicu1y': '70',
  'image-073-30-south-kis7bz': '70',
};
// Responsive rungs. The largest rung also caps the "full" WebP — nothing on
// the site renders wider than ~2000 CSS px.
const WIDTHS = [800, 1280, 2000];

const files = (await fs.readdir(imagesDir)).filter((f) => /\.(jpe?g|png)$/i.test(f)).sort();

/** @type {Record<string, { width: number; height: number; variants: { src: string; w: number }[] }>} */
const manifest = {};

for (const file of files) {
  const abs = path.join(imagesDir, file);
  const { stdout } = await run('magick', ['identify', '-format', '%w %h', abs]);
  const [width, height] = stdout.trim().split(' ').map(Number);
  const stem = file.replace(/\.(jpe?g|png)$/i, '');

  // Rungs strictly below the source width, plus the source width itself capped
  // at the largest rung (nothing renders wider than that).
  const rungs = [...new Set([...WIDTHS.filter((w) => w < width), Math.min(width, WIDTHS[WIDTHS.length - 1])])].sort(
    (a, b) => a - b,
  );

  const variants = [];
  for (const target of rungs) {
    const outName = `${stem}-${target}w.webp`;
    const out = path.join(imagesDir, outName);
    let need = true;
    try {
      const [srcStat, outStat] = await Promise.all([fs.stat(abs), fs.stat(out)]);
      need = outStat.mtimeMs < srcStat.mtimeMs;
    } catch {
      need = true;
    }
    if (need) {
      await run('magick', [abs, '-auto-orient', '-resize', `${target}x>`, '-quality', QUALITY_OVERRIDES[stem] ?? QUALITY, out]);
    }
    variants.push({ src: `/images/${outName}`, w: target });
    if (target === width) break; // original narrower than this rung; stop
  }
  // Deduplicate rungs that collapsed to the same width
  const seen = new Set();
  const unique = variants.filter((v) => !seen.has(v.w) && seen.add(v.w));

  manifest[`/images/${file}`] = { width, height, variants: unique };
}

const header = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Maps original image paths to intrinsic dimensions + generated WebP variants.

export interface ImageVariant {
  src: string;
  w: number;
}

export interface ImageMeta {
  width: number;
  height: number;
  variants: ImageVariant[];
}

export const IMAGE_MANIFEST: Record<string, ImageMeta> = `;

await fs.writeFile(manifestPath, header + JSON.stringify(manifest, null, 2) + ';\n', 'utf8');
console.log(`Optimized ${files.length} images; manifest written to ${path.relative(root, manifestPath)}.`);
