// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Maps original image paths to intrinsic dimensions + generated WebP/AVIF variants.

export interface ImageVariant {
  src: string;
  /** Absent when the AVIF encode couldn't beat the WebP twin's size. */
  avif?: string;
  w: number;
}

export interface ImageMeta {
  width: number;
  height: number;
  variants: ImageVariant[];
}

export const IMAGE_MANIFEST: Record<string, ImageMeta> = {
  "/images/exhibit-logo.png": {
    "width": 1805,
    "height": 621,
    "variants": [
      {
        "src": "/images/exhibit-logo-320w.webp",
        "avif": "/images/exhibit-logo-320w.avif",
        "w": 320
      },
      {
        "src": "/images/exhibit-logo-800w.webp",
        "avif": "/images/exhibit-logo-800w.avif",
        "w": 800
      },
      {
        "src": "/images/exhibit-logo-1280w.webp",
        "avif": "/images/exhibit-logo-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/exhibit-logo-1805w.webp",
        "avif": "/images/exhibit-logo-1805w.avif",
        "w": 1805
      }
    ]
  },
  "/images/image-001-exhibit-on-superior-logo-color-a7pvg4.png": {
    "width": 1805,
    "height": 621,
    "variants": [
      {
        "src": "/images/image-001-exhibit-on-superior-logo-color-a7pvg4-320w.webp",
        "avif": "/images/image-001-exhibit-on-superior-logo-color-a7pvg4-320w.avif",
        "w": 320
      },
      {
        "src": "/images/image-001-exhibit-on-superior-logo-color-a7pvg4-800w.webp",
        "avif": "/images/image-001-exhibit-on-superior-logo-color-a7pvg4-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-001-exhibit-on-superior-logo-color-a7pvg4-1280w.webp",
        "avif": "/images/image-001-exhibit-on-superior-logo-color-a7pvg4-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-001-exhibit-on-superior-logo-color-a7pvg4-1805w.webp",
        "avif": "/images/image-001-exhibit-on-superior-logo-color-a7pvg4-1805w.avif",
        "w": 1805
      }
    ]
  },
  "/images/image-002-gettyimages-1286580777-nvdupq.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-002-gettyimages-1286580777-nvdupq-800w.webp",
        "avif": "/images/image-002-gettyimages-1286580777-nvdupq-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-002-gettyimages-1286580777-nvdupq-1280w.webp",
        "avif": "/images/image-002-gettyimages-1286580777-nvdupq-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-002-gettyimages-1286580777-nvdupq-2000w.webp",
        "avif": "/images/image-002-gettyimages-1286580777-nvdupq-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-003-gettyimages-1216663469-cc9uxz.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-003-gettyimages-1216663469-cc9uxz-800w.webp",
        "avif": "/images/image-003-gettyimages-1216663469-cc9uxz-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-003-gettyimages-1216663469-cc9uxz-1280w.webp",
        "avif": "/images/image-003-gettyimages-1216663469-cc9uxz-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-003-gettyimages-1216663469-cc9uxz-2000w.webp",
        "avif": "/images/image-003-gettyimages-1216663469-cc9uxz-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-004-012417-5732-pu4fo5.jpg": {
    "width": 2000,
    "height": 1477,
    "variants": [
      {
        "src": "/images/image-004-012417-5732-pu4fo5-800w.webp",
        "avif": "/images/image-004-012417-5732-pu4fo5-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-004-012417-5732-pu4fo5-1280w.webp",
        "avif": "/images/image-004-012417-5732-pu4fo5-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-004-012417-5732-pu4fo5-2000w.webp",
        "avif": "/images/image-004-012417-5732-pu4fo5-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-009-34-southeast-levwhc.jpg": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/image-009-34-southeast-levwhc-800w.webp",
        "avif": "/images/image-009-34-southeast-levwhc-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-009-34-southeast-levwhc-1200w.webp",
        "avif": "/images/image-009-34-southeast-levwhc-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/image-010-full-floor-amenity-deck-overlooking-the-city-and.jpg": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/image-010-full-floor-amenity-deck-overlooking-the-city-and-800w.webp",
        "avif": "/images/image-010-full-floor-amenity-deck-overlooking-the-city-and-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-010-full-floor-amenity-deck-overlooking-the-city-and-1200w.webp",
        "avif": "/images/image-010-full-floor-amenity-deck-overlooking-the-city-and-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/image-011-20170808-0713-n8k48b.jpg": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/image-011-20170808-0713-n8k48b-800w.webp",
        "avif": "/images/image-011-20170808-0713-n8k48b-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-011-20170808-0713-n8k48b-1200w.webp",
        "avif": "/images/image-011-20170808-0713-n8k48b-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/image-012-012417-6415-hgfghu.jpg": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/image-012-012417-6415-hgfghu-800w.webp",
        "avif": "/images/image-012-012417-6415-hgfghu-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-012-012417-6415-hgfghu-1200w.webp",
        "avif": "/images/image-012-012417-6415-hgfghu-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/image-013-20170808-0861-n4esrp.jpg": {
    "width": 2000,
    "height": 1167,
    "variants": [
      {
        "src": "/images/image-013-20170808-0861-n4esrp-800w.webp",
        "avif": "/images/image-013-20170808-0861-n4esrp-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-013-20170808-0861-n4esrp-1280w.webp",
        "avif": "/images/image-013-20170808-0861-n4esrp-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-013-20170808-0861-n4esrp-2000w.webp",
        "avif": "/images/image-013-20170808-0861-n4esrp-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-014-exhibit-living-room-n5xrna.jpg": {
    "width": 2000,
    "height": 1167,
    "variants": [
      {
        "src": "/images/image-014-exhibit-living-room-n5xrna-800w.webp",
        "avif": "/images/image-014-exhibit-living-room-n5xrna-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-014-exhibit-living-room-n5xrna-1280w.webp",
        "avif": "/images/image-014-exhibit-living-room-n5xrna-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-014-exhibit-living-room-n5xrna-2000w.webp",
        "avif": "/images/image-014-exhibit-living-room-n5xrna-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-015-work-spaces-with-blazing-fast-wifi-access-lzfatq.jpg": {
    "width": 2000,
    "height": 1167,
    "variants": [
      {
        "src": "/images/image-015-work-spaces-with-blazing-fast-wifi-access-lzfatq-800w.webp",
        "avif": "/images/image-015-work-spaces-with-blazing-fast-wifi-access-lzfatq-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-015-work-spaces-with-blazing-fast-wifi-access-lzfatq-1280w.webp",
        "avif": "/images/image-015-work-spaces-with-blazing-fast-wifi-access-lzfatq-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-015-work-spaces-with-blazing-fast-wifi-access-lzfatq-2000w.webp",
        "avif": "/images/image-015-work-spaces-with-blazing-fast-wifi-access-lzfatq-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-016-012417-6396-e1vomm.jpg": {
    "width": 2000,
    "height": 1167,
    "variants": [
      {
        "src": "/images/image-016-012417-6396-e1vomm-800w.webp",
        "avif": "/images/image-016-012417-6396-e1vomm-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-016-012417-6396-e1vomm-1280w.webp",
        "avif": "/images/image-016-012417-6396-e1vomm-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-016-012417-6396-e1vomm-2000w.webp",
        "avif": "/images/image-016-012417-6396-e1vomm-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-017-012417-6521-i8yuom.jpg": {
    "width": 2000,
    "height": 1167,
    "variants": [
      {
        "src": "/images/image-017-012417-6521-i8yuom-800w.webp",
        "avif": "/images/image-017-012417-6521-i8yuom-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-017-012417-6521-i8yuom-1280w.webp",
        "avif": "/images/image-017-012417-6521-i8yuom-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-017-012417-6521-i8yuom-2000w.webp",
        "avif": "/images/image-017-012417-6521-i8yuom-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-018-lounge-with-fireplace-and-big-screen-tv-ymvrom.jpg": {
    "width": 2000,
    "height": 1167,
    "variants": [
      {
        "src": "/images/image-018-lounge-with-fireplace-and-big-screen-tv-ymvrom-800w.webp",
        "avif": "/images/image-018-lounge-with-fireplace-and-big-screen-tv-ymvrom-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-018-lounge-with-fireplace-and-big-screen-tv-ymvrom-1280w.webp",
        "avif": "/images/image-018-lounge-with-fireplace-and-big-screen-tv-ymvrom-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-018-lounge-with-fireplace-and-big-screen-tv-ymvrom-2000w.webp",
        "avif": "/images/image-018-lounge-with-fireplace-and-big-screen-tv-ymvrom-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-019-game-area-with-arcade-games-and-wall-scrabble-oz.jpg": {
    "width": 2000,
    "height": 1167,
    "variants": [
      {
        "src": "/images/image-019-game-area-with-arcade-games-and-wall-scrabble-oz-800w.webp",
        "avif": "/images/image-019-game-area-with-arcade-games-and-wall-scrabble-oz-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-019-game-area-with-arcade-games-and-wall-scrabble-oz-1280w.webp",
        "avif": "/images/image-019-game-area-with-arcade-games-and-wall-scrabble-oz-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-019-game-area-with-arcade-games-and-wall-scrabble-oz-2000w.webp",
        "avif": "/images/image-019-game-area-with-arcade-games-and-wall-scrabble-oz-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-020-dsc00806-yr6rhk.jpg": {
    "width": 2000,
    "height": 1167,
    "variants": [
      {
        "src": "/images/image-020-dsc00806-yr6rhk-800w.webp",
        "avif": "/images/image-020-dsc00806-yr6rhk-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-020-dsc00806-yr6rhk-1280w.webp",
        "avif": "/images/image-020-dsc00806-yr6rhk-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-020-dsc00806-yr6rhk-2000w.webp",
        "avif": "/images/image-020-dsc00806-yr6rhk-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-021-20170808-0852-sw1ncm.jpg": {
    "width": 2000,
    "height": 1167,
    "variants": [
      {
        "src": "/images/image-021-20170808-0852-sw1ncm-800w.webp",
        "avif": "/images/image-021-20170808-0852-sw1ncm-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-021-20170808-0852-sw1ncm-1280w.webp",
        "avif": "/images/image-021-20170808-0852-sw1ncm-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-021-20170808-0852-sw1ncm-2000w.webp",
        "avif": "/images/image-021-20170808-0852-sw1ncm-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-023-gettyimages-639122762-qpfmh0.jpg": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/image-023-gettyimages-639122762-qpfmh0-800w.webp",
        "avif": "/images/image-023-gettyimages-639122762-qpfmh0-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-023-gettyimages-639122762-qpfmh0-1200w.webp",
        "avif": "/images/image-023-gettyimages-639122762-qpfmh0-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/image-024-gettyimages-1464613356-q7z583.jpg": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/image-024-gettyimages-1464613356-q7z583-800w.webp",
        "avif": "/images/image-024-gettyimages-1464613356-q7z583-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-024-gettyimages-1464613356-q7z583-1200w.webp",
        "avif": "/images/image-024-gettyimages-1464613356-q7z583-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/image-025-gettyimages-1694195877-kb4dln.jpg": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/image-025-gettyimages-1694195877-kb4dln-800w.webp",
        "avif": "/images/image-025-gettyimages-1694195877-kb4dln-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-025-gettyimages-1694195877-kb4dln-1200w.webp",
        "avif": "/images/image-025-gettyimages-1694195877-kb4dln-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/image-026-gettyimages-2169911981-his7ly.jpg": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/image-026-gettyimages-2169911981-his7ly-800w.webp",
        "avif": "/images/image-026-gettyimages-2169911981-his7ly-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-026-gettyimages-2169911981-his7ly-1200w.webp",
        "avif": "/images/image-026-gettyimages-2169911981-his7ly-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/image-030-012417-5663-hxwee6.jpg": {
    "width": 2000,
    "height": 500,
    "variants": [
      {
        "src": "/images/image-030-012417-5663-hxwee6-800w.webp",
        "avif": "/images/image-030-012417-5663-hxwee6-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-030-012417-5663-hxwee6-1280w.webp",
        "avif": "/images/image-030-012417-5663-hxwee6-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-030-012417-5663-hxwee6-2000w.webp",
        "avif": "/images/image-030-012417-5663-hxwee6-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-031-012417-5607-piqxtr.jpg": {
    "width": 1200,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-031-012417-5607-piqxtr-800w.webp",
        "avif": "/images/image-031-012417-5607-piqxtr-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-031-012417-5607-piqxtr-1200w.webp",
        "avif": "/images/image-031-012417-5607-piqxtr-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/image-033-lounge-mfioa0.jpg": {
    "width": 2000,
    "height": 500,
    "variants": [
      {
        "src": "/images/image-033-lounge-mfioa0-800w.webp",
        "avif": "/images/image-033-lounge-mfioa0-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-033-lounge-mfioa0-1280w.webp",
        "avif": "/images/image-033-lounge-mfioa0-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-033-lounge-mfioa0-2000w.webp",
        "avif": "/images/image-033-lounge-mfioa0-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-034-012417-5663-hxwee6.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-034-012417-5663-hxwee6-800w.webp",
        "avif": "/images/image-034-012417-5663-hxwee6-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-034-012417-5663-hxwee6-1280w.webp",
        "avif": "/images/image-034-012417-5663-hxwee6-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-034-012417-5663-hxwee6-2000w.webp",
        "avif": "/images/image-034-012417-5663-hxwee6-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-035-012417-5680-yegi2f.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-035-012417-5680-yegi2f-800w.webp",
        "avif": "/images/image-035-012417-5680-yegi2f-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-035-012417-5680-yegi2f-1280w.webp",
        "avif": "/images/image-035-012417-5680-yegi2f-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-035-012417-5680-yegi2f-2000w.webp",
        "avif": "/images/image-035-012417-5680-yegi2f-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-036-012417-5793-ebbynh.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-036-012417-5793-ebbynh-800w.webp",
        "avif": "/images/image-036-012417-5793-ebbynh-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-036-012417-5793-ebbynh-1280w.webp",
        "avif": "/images/image-036-012417-5793-ebbynh-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-036-012417-5793-ebbynh-2000w.webp",
        "avif": "/images/image-036-012417-5793-ebbynh-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-037-012417-5630-zsx9za.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-037-012417-5630-zsx9za-800w.webp",
        "avif": "/images/image-037-012417-5630-zsx9za-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-037-012417-5630-zsx9za-1280w.webp",
        "avif": "/images/image-037-012417-5630-zsx9za-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-037-012417-5630-zsx9za-2000w.webp",
        "avif": "/images/image-037-012417-5630-zsx9za-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-038-012417-6039-adwhss.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-038-012417-6039-adwhss-800w.webp",
        "avif": "/images/image-038-012417-6039-adwhss-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-038-012417-6039-adwhss-1280w.webp",
        "avif": "/images/image-038-012417-6039-adwhss-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-038-012417-6039-adwhss-2000w.webp",
        "avif": "/images/image-038-012417-6039-adwhss-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-039-012417-5797-pnyuww.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-039-012417-5797-pnyuww-800w.webp",
        "avif": "/images/image-039-012417-5797-pnyuww-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-039-012417-5797-pnyuww-1280w.webp",
        "avif": "/images/image-039-012417-5797-pnyuww-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-039-012417-5797-pnyuww-2000w.webp",
        "avif": "/images/image-039-012417-5797-pnyuww-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-040-012417-5616b-x84gwq.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-040-012417-5616b-x84gwq-800w.webp",
        "avif": "/images/image-040-012417-5616b-x84gwq-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-040-012417-5616b-x84gwq-1280w.webp",
        "avif": "/images/image-040-012417-5616b-x84gwq-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-040-012417-5616b-x84gwq-2000w.webp",
        "avif": "/images/image-040-012417-5616b-x84gwq-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-041-012417-5607-piqxtr.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-041-012417-5607-piqxtr-800w.webp",
        "avif": "/images/image-041-012417-5607-piqxtr-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-041-012417-5607-piqxtr-1280w.webp",
        "avif": "/images/image-041-012417-5607-piqxtr-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-041-012417-5607-piqxtr-2000w.webp",
        "avif": "/images/image-041-012417-5607-piqxtr-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-042-012417-5548-cyorgo.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-042-012417-5548-cyorgo-800w.webp",
        "avif": "/images/image-042-012417-5548-cyorgo-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-042-012417-5548-cyorgo-1280w.webp",
        "avif": "/images/image-042-012417-5548-cyorgo-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-042-012417-5548-cyorgo-2000w.webp",
        "avif": "/images/image-042-012417-5548-cyorgo-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-043-012417-5563-oriwf6.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-043-012417-5563-oriwf6-800w.webp",
        "avif": "/images/image-043-012417-5563-oriwf6-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-043-012417-5563-oriwf6-1280w.webp",
        "avif": "/images/image-043-012417-5563-oriwf6-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-043-012417-5563-oriwf6-2000w.webp",
        "avif": "/images/image-043-012417-5563-oriwf6-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-044-012417-5578-ttpmgd.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-044-012417-5578-ttpmgd-800w.webp",
        "avif": "/images/image-044-012417-5578-ttpmgd-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-044-012417-5578-ttpmgd-1280w.webp",
        "avif": "/images/image-044-012417-5578-ttpmgd-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-044-012417-5578-ttpmgd-2000w.webp",
        "avif": "/images/image-044-012417-5578-ttpmgd-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-045-012417-5719-d9ekn6.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-045-012417-5719-d9ekn6-800w.webp",
        "avif": "/images/image-045-012417-5719-d9ekn6-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-045-012417-5719-d9ekn6-1280w.webp",
        "avif": "/images/image-045-012417-5719-d9ekn6-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-045-012417-5719-d9ekn6-2000w.webp",
        "avif": "/images/image-045-012417-5719-d9ekn6-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-046-012417-5990-n11px5.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-046-012417-5990-n11px5-800w.webp",
        "avif": "/images/image-046-012417-5990-n11px5-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-046-012417-5990-n11px5-1280w.webp",
        "avif": "/images/image-046-012417-5990-n11px5-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-046-012417-5990-n11px5-2000w.webp",
        "avif": "/images/image-046-012417-5990-n11px5-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-047-012417-6106-pktrcl.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-047-012417-6106-pktrcl-800w.webp",
        "avif": "/images/image-047-012417-6106-pktrcl-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-047-012417-6106-pktrcl-1280w.webp",
        "avif": "/images/image-047-012417-6106-pktrcl-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-047-012417-6106-pktrcl-2000w.webp",
        "avif": "/images/image-047-012417-6106-pktrcl-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-048-012417-5784-mqhldb.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-048-012417-5784-mqhldb-800w.webp",
        "avif": "/images/image-048-012417-5784-mqhldb-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-048-012417-5784-mqhldb-1280w.webp",
        "avif": "/images/image-048-012417-5784-mqhldb-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-048-012417-5784-mqhldb-2000w.webp",
        "avif": "/images/image-048-012417-5784-mqhldb-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-049-012417-5711-tfyt08.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-049-012417-5711-tfyt08-800w.webp",
        "avif": "/images/image-049-012417-5711-tfyt08-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-049-012417-5711-tfyt08-1280w.webp",
        "avif": "/images/image-049-012417-5711-tfyt08-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-049-012417-5711-tfyt08-2000w.webp",
        "avif": "/images/image-049-012417-5711-tfyt08-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-050-012417-5857-ihelta.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-050-012417-5857-ihelta-800w.webp",
        "avif": "/images/image-050-012417-5857-ihelta-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-050-012417-5857-ihelta-1280w.webp",
        "avif": "/images/image-050-012417-5857-ihelta-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-050-012417-5857-ihelta-2000w.webp",
        "avif": "/images/image-050-012417-5857-ihelta-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-051-012417-5582-dbyi1b.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-051-012417-5582-dbyi1b-800w.webp",
        "avif": "/images/image-051-012417-5582-dbyi1b-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-051-012417-5582-dbyi1b-1280w.webp",
        "avif": "/images/image-051-012417-5582-dbyi1b-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-051-012417-5582-dbyi1b-2000w.webp",
        "avif": "/images/image-051-012417-5582-dbyi1b-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-052-012417-5599-xirys3.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-052-012417-5599-xirys3-800w.webp",
        "avif": "/images/image-052-012417-5599-xirys3-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-052-012417-5599-xirys3-1280w.webp",
        "avif": "/images/image-052-012417-5599-xirys3-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-052-012417-5599-xirys3-2000w.webp",
        "avif": "/images/image-052-012417-5599-xirys3-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-053-012417-5817-fvbupj.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-053-012417-5817-fvbupj-800w.webp",
        "avif": "/images/image-053-012417-5817-fvbupj-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-053-012417-5817-fvbupj-1280w.webp",
        "avif": "/images/image-053-012417-5817-fvbupj-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-053-012417-5817-fvbupj-2000w.webp",
        "avif": "/images/image-053-012417-5817-fvbupj-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-054-20170808-0677-qicu1y.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-054-20170808-0677-qicu1y-800w.webp",
        "avif": "/images/image-054-20170808-0677-qicu1y-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-054-20170808-0677-qicu1y-1280w.webp",
        "avif": "/images/image-054-20170808-0677-qicu1y-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-054-20170808-0677-qicu1y-2000w.webp",
        "avif": "/images/image-054-20170808-0677-qicu1y-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-055-dji-20230620092832-0149-d-yrh5eg.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-055-dji-20230620092832-0149-d-yrh5eg-800w.webp",
        "avif": "/images/image-055-dji-20230620092832-0149-d-yrh5eg-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-055-dji-20230620092832-0149-d-yrh5eg-1280w.webp",
        "avif": "/images/image-055-dji-20230620092832-0149-d-yrh5eg-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-055-dji-20230620092832-0149-d-yrh5eg-2000w.webp",
        "avif": "/images/image-055-dji-20230620092832-0149-d-yrh5eg-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-056-20170808-0721-c60hfw.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-056-20170808-0721-c60hfw-800w.webp",
        "avif": "/images/image-056-20170808-0721-c60hfw-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-056-20170808-0721-c60hfw-1280w.webp",
        "avif": "/images/image-056-20170808-0721-c60hfw-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-056-20170808-0721-c60hfw-2000w.webp",
        "avif": "/images/image-056-20170808-0721-c60hfw-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-057-dji-20230620092900-0153-d-oaedvz.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-057-dji-20230620092900-0153-d-oaedvz-800w.webp",
        "avif": "/images/image-057-dji-20230620092900-0153-d-oaedvz-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-057-dji-20230620092900-0153-d-oaedvz-1280w.webp",
        "avif": "/images/image-057-dji-20230620092900-0153-d-oaedvz-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-057-dji-20230620092900-0153-d-oaedvz-2000w.webp",
        "avif": "/images/image-057-dji-20230620092900-0153-d-oaedvz-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-058-20170808-0843-ymrdpp.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-058-20170808-0843-ymrdpp-800w.webp",
        "avif": "/images/image-058-20170808-0843-ymrdpp-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-058-20170808-0843-ymrdpp-1280w.webp",
        "avif": "/images/image-058-20170808-0843-ymrdpp-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-058-20170808-0843-ymrdpp-2000w.webp",
        "avif": "/images/image-058-20170808-0843-ymrdpp-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-059-20170808-0852-sw1ncm.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-059-20170808-0852-sw1ncm-800w.webp",
        "avif": "/images/image-059-20170808-0852-sw1ncm-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-059-20170808-0852-sw1ncm-1280w.webp",
        "avif": "/images/image-059-20170808-0852-sw1ncm-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-059-20170808-0852-sw1ncm-2000w.webp",
        "avif": "/images/image-059-20170808-0852-sw1ncm-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-060-bt7b3585b-ykt6yu.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-060-bt7b3585b-ykt6yu-800w.webp",
        "avif": "/images/image-060-bt7b3585b-ykt6yu-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-060-bt7b3585b-ykt6yu-1280w.webp",
        "avif": "/images/image-060-bt7b3585b-ykt6yu-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-060-bt7b3585b-ykt6yu-2000w.webp",
        "avif": "/images/image-060-bt7b3585b-ykt6yu-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-061-012417-6396-e1vomm.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-061-012417-6396-e1vomm-800w.webp",
        "avif": "/images/image-061-012417-6396-e1vomm-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-061-012417-6396-e1vomm-1280w.webp",
        "avif": "/images/image-061-012417-6396-e1vomm-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-061-012417-6396-e1vomm-2000w.webp",
        "avif": "/images/image-061-012417-6396-e1vomm-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-062-012417-6604-a7yglt.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-062-012417-6604-a7yglt-800w.webp",
        "avif": "/images/image-062-012417-6604-a7yglt-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-062-012417-6604-a7yglt-1280w.webp",
        "avif": "/images/image-062-012417-6604-a7yglt-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-062-012417-6604-a7yglt-2000w.webp",
        "avif": "/images/image-062-012417-6604-a7yglt-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-063-012417-6437-nx2ske.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-063-012417-6437-nx2ske-800w.webp",
        "avif": "/images/image-063-012417-6437-nx2ske-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-063-012417-6437-nx2ske-1280w.webp",
        "avif": "/images/image-063-012417-6437-nx2ske-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-063-012417-6437-nx2ske-2000w.webp",
        "avif": "/images/image-063-012417-6437-nx2ske-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-064-012417-6469-s4tipl.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-064-012417-6469-s4tipl-800w.webp",
        "avif": "/images/image-064-012417-6469-s4tipl-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-064-012417-6469-s4tipl-1280w.webp",
        "avif": "/images/image-064-012417-6469-s4tipl-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-064-012417-6469-s4tipl-2000w.webp",
        "avif": "/images/image-064-012417-6469-s4tipl-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-065-012417-6521-i8yuom.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-065-012417-6521-i8yuom-800w.webp",
        "avif": "/images/image-065-012417-6521-i8yuom-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-065-012417-6521-i8yuom-1280w.webp",
        "avif": "/images/image-065-012417-6521-i8yuom-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-065-012417-6521-i8yuom-2000w.webp",
        "avif": "/images/image-065-012417-6521-i8yuom-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-066-game-area-with-arcade-games-and-wall-scrabble-oz.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-066-game-area-with-arcade-games-and-wall-scrabble-oz-800w.webp",
        "avif": "/images/image-066-game-area-with-arcade-games-and-wall-scrabble-oz-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-066-game-area-with-arcade-games-and-wall-scrabble-oz-1280w.webp",
        "avif": "/images/image-066-game-area-with-arcade-games-and-wall-scrabble-oz-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-066-game-area-with-arcade-games-and-wall-scrabble-oz-2000w.webp",
        "avif": "/images/image-066-game-area-with-arcade-games-and-wall-scrabble-oz-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-067-tech-lounge-with-charging-station-and-kitchen-gh.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-067-tech-lounge-with-charging-station-and-kitchen-gh-800w.webp",
        "avif": "/images/image-067-tech-lounge-with-charging-station-and-kitchen-gh-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-067-tech-lounge-with-charging-station-and-kitchen-gh-1280w.webp",
        "avif": "/images/image-067-tech-lounge-with-charging-station-and-kitchen-gh-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-067-tech-lounge-with-charging-station-and-kitchen-gh-2000w.webp",
        "avif": "/images/image-067-tech-lounge-with-charging-station-and-kitchen-gh-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-068-dsc00897-gc3ypb.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-068-dsc00897-gc3ypb-800w.webp",
        "avif": "/images/image-068-dsc00897-gc3ypb-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-068-dsc00897-gc3ypb-1280w.webp",
        "avif": "/images/image-068-dsc00897-gc3ypb-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-068-dsc00897-gc3ypb-2000w.webp",
        "avif": "/images/image-068-dsc00897-gc3ypb-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-069-012417-6379-oiufjz.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-069-012417-6379-oiufjz-800w.webp",
        "avif": "/images/image-069-012417-6379-oiufjz-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-069-012417-6379-oiufjz-1280w.webp",
        "avif": "/images/image-069-012417-6379-oiufjz-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-069-012417-6379-oiufjz-2000w.webp",
        "avif": "/images/image-069-012417-6379-oiufjz-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-070-012417-6535-gpdv36.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-070-012417-6535-gpdv36-800w.webp",
        "avif": "/images/image-070-012417-6535-gpdv36-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-070-012417-6535-gpdv36-1280w.webp",
        "avif": "/images/image-070-012417-6535-gpdv36-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-070-012417-6535-gpdv36-2000w.webp",
        "avif": "/images/image-070-012417-6535-gpdv36-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-071-bt7b3592-gtyc1i.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-071-bt7b3592-gtyc1i-800w.webp",
        "avif": "/images/image-071-bt7b3592-gtyc1i-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-071-bt7b3592-gtyc1i-1280w.webp",
        "avif": "/images/image-071-bt7b3592-gtyc1i-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-071-bt7b3592-gtyc1i-2000w.webp",
        "avif": "/images/image-071-bt7b3592-gtyc1i-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-072-30-north-runyfq.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-072-30-north-runyfq-800w.webp",
        "avif": "/images/image-072-30-north-runyfq-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-072-30-north-runyfq-1280w.webp",
        "avif": "/images/image-072-30-north-runyfq-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-072-30-north-runyfq-2000w.webp",
        "avif": "/images/image-072-30-north-runyfq-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-073-30-south-kis7bz.jpg": {
    "width": 2000,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-073-30-south-kis7bz-800w.webp",
        "avif": "/images/image-073-30-south-kis7bz-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-073-30-south-kis7bz-1280w.webp",
        "avif": "/images/image-073-30-south-kis7bz-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-073-30-south-kis7bz-2000w.webp",
        "avif": "/images/image-073-30-south-kis7bz-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-074-game-area-with-arcade-games-and-wall-scrabble-ej.jpg": {
    "width": 2000,
    "height": 500,
    "variants": [
      {
        "src": "/images/image-074-game-area-with-arcade-games-and-wall-scrabble-ej-800w.webp",
        "avif": "/images/image-074-game-area-with-arcade-games-and-wall-scrabble-ej-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-074-game-area-with-arcade-games-and-wall-scrabble-ej-1280w.webp",
        "avif": "/images/image-074-game-area-with-arcade-games-and-wall-scrabble-ej-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-074-game-area-with-arcade-games-and-wall-scrabble-ej-2000w.webp",
        "avif": "/images/image-074-game-area-with-arcade-games-and-wall-scrabble-ej-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-075-20170601-0036-z1fw1i.jpg": {
    "width": 2000,
    "height": 500,
    "variants": [
      {
        "src": "/images/image-075-20170601-0036-z1fw1i-800w.webp",
        "avif": "/images/image-075-20170601-0036-z1fw1i-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-075-20170601-0036-z1fw1i-1280w.webp",
        "avif": "/images/image-075-20170601-0036-z1fw1i-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-075-20170601-0036-z1fw1i-2000w.webp",
        "avif": "/images/image-075-20170601-0036-z1fw1i-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-079-gettyimages-1440280890-ox4ske.jpg": {
    "width": 2000,
    "height": 500,
    "variants": [
      {
        "src": "/images/image-079-gettyimages-1440280890-ox4ske-800w.webp",
        "avif": "/images/image-079-gettyimages-1440280890-ox4ske-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-079-gettyimages-1440280890-ox4ske-1280w.webp",
        "avif": "/images/image-079-gettyimages-1440280890-ox4ske-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-079-gettyimages-1440280890-ox4ske-2000w.webp",
        "avif": "/images/image-079-gettyimages-1440280890-ox4ske-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-080-gettyimages-1386939001-lrrzhc.jpg": {
    "width": 1200,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-080-gettyimages-1386939001-lrrzhc-800w.webp",
        "avif": "/images/image-080-gettyimages-1386939001-lrrzhc-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-080-gettyimages-1386939001-lrrzhc-1200w.webp",
        "avif": "/images/image-080-gettyimages-1386939001-lrrzhc-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/image-081-20170926-1450-wmbiod.jpg": {
    "width": 2000,
    "height": 500,
    "variants": [
      {
        "src": "/images/image-081-20170926-1450-wmbiod-800w.webp",
        "avif": "/images/image-081-20170926-1450-wmbiod-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-081-20170926-1450-wmbiod-1280w.webp",
        "avif": "/images/image-081-20170926-1450-wmbiod-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-081-20170926-1450-wmbiod-2000w.webp",
        "avif": "/images/image-081-20170926-1450-wmbiod-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-082-bt7b3562-adimkf.jpg": {
    "width": 1200,
    "height": 800,
    "variants": [
      {
        "src": "/images/image-082-bt7b3562-adimkf-800w.webp",
        "avif": "/images/image-082-bt7b3562-adimkf-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-082-bt7b3562-adimkf-1200w.webp",
        "avif": "/images/image-082-bt7b3562-adimkf-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/image-084-20170601-0076-p0s5be.jpg": {
    "width": 2000,
    "height": 500,
    "variants": [
      {
        "src": "/images/image-084-20170601-0076-p0s5be-800w.webp",
        "avif": "/images/image-084-20170601-0076-p0s5be-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-084-20170601-0076-p0s5be-1280w.webp",
        "avif": "/images/image-084-20170601-0076-p0s5be-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-084-20170601-0076-p0s5be-2000w.webp",
        "avif": "/images/image-084-20170601-0076-p0s5be-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-085-30-south-kis7bz.jpg": {
    "width": 2000,
    "height": 500,
    "variants": [
      {
        "src": "/images/image-085-30-south-kis7bz-800w.webp",
        "avif": "/images/image-085-30-south-kis7bz-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-085-30-south-kis7bz-1280w.webp",
        "avif": "/images/image-085-30-south-kis7bz-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-085-30-south-kis7bz-2000w.webp",
        "avif": "/images/image-085-30-south-kis7bz-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-086-work-spaces-with-blazing-fast-wifi-access-d3tr2q.jpg": {
    "width": 2000,
    "height": 500,
    "variants": [
      {
        "src": "/images/image-086-work-spaces-with-blazing-fast-wifi-access-d3tr2q-800w.webp",
        "avif": "/images/image-086-work-spaces-with-blazing-fast-wifi-access-d3tr2q-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-086-work-spaces-with-blazing-fast-wifi-access-d3tr2q-1280w.webp",
        "avif": "/images/image-086-work-spaces-with-blazing-fast-wifi-access-d3tr2q-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-086-work-spaces-with-blazing-fast-wifi-access-d3tr2q-2000w.webp",
        "avif": "/images/image-086-work-spaces-with-blazing-fast-wifi-access-d3tr2q-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-087-012417-5548-ocwsdh.jpg": {
    "width": 2000,
    "height": 500,
    "variants": [
      {
        "src": "/images/image-087-012417-5548-ocwsdh-800w.webp",
        "avif": "/images/image-087-012417-5548-ocwsdh-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-087-012417-5548-ocwsdh-1280w.webp",
        "avif": "/images/image-087-012417-5548-ocwsdh-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-087-012417-5548-ocwsdh-2000w.webp",
        "avif": "/images/image-087-012417-5548-ocwsdh-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/image-088-20170808-0868-1-odeo9b.jpg": {
    "width": 2000,
    "height": 500,
    "variants": [
      {
        "src": "/images/image-088-20170808-0868-1-odeo9b-800w.webp",
        "avif": "/images/image-088-20170808-0868-1-odeo9b-800w.avif",
        "w": 800
      },
      {
        "src": "/images/image-088-20170808-0868-1-odeo9b-1280w.webp",
        "avif": "/images/image-088-20170808-0868-1-odeo9b-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/image-088-20170808-0868-1-odeo9b-2000w.webp",
        "avif": "/images/image-088-20170808-0868-1-odeo9b-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/matterport-poster-amenities.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/images/matterport-poster-amenities-800w.webp",
        "avif": "/images/matterport-poster-amenities-800w.avif",
        "w": 800
      },
      {
        "src": "/images/matterport-poster-amenities-1280w.webp",
        "avif": "/images/matterport-poster-amenities-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/matterport-poster-amenities-1920w.webp",
        "avif": "/images/matterport-poster-amenities-1920w.avif",
        "w": 1920
      }
    ]
  },
  "/images/matterport-poster-exhibit-2104.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/images/matterport-poster-exhibit-2104-800w.webp",
        "avif": "/images/matterport-poster-exhibit-2104-800w.avif",
        "w": 800
      },
      {
        "src": "/images/matterport-poster-exhibit-2104-1280w.webp",
        "avif": "/images/matterport-poster-exhibit-2104-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/matterport-poster-exhibit-2104-2000w.webp",
        "avif": "/images/matterport-poster-exhibit-2104-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/matterport-poster-exhibit-605.jpg": {
    "width": 2880,
    "height": 1620,
    "variants": [
      {
        "src": "/images/matterport-poster-exhibit-605-800w.webp",
        "avif": "/images/matterport-poster-exhibit-605-800w.avif",
        "w": 800
      },
      {
        "src": "/images/matterport-poster-exhibit-605-1280w.webp",
        "avif": "/images/matterport-poster-exhibit-605-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/matterport-poster-exhibit-605-2000w.webp",
        "avif": "/images/matterport-poster-exhibit-605-2000w.avif",
        "w": 2000
      }
    ]
  },
  "/images/og-card.jpg": {
    "width": 1200,
    "height": 630,
    "variants": [
      {
        "src": "/images/og-card-800w.webp",
        "avif": "/images/og-card-800w.avif",
        "w": 800
      },
      {
        "src": "/images/og-card-1200w.webp",
        "avif": "/images/og-card-1200w.avif",
        "w": 1200
      }
    ]
  },
  "/images/vimeo-poster-life-at-exhibit.jpg": {
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "src": "/images/vimeo-poster-life-at-exhibit-800w.webp",
        "avif": "/images/vimeo-poster-life-at-exhibit-800w.avif",
        "w": 800
      },
      {
        "src": "/images/vimeo-poster-life-at-exhibit-1280w.webp",
        "avif": "/images/vimeo-poster-life-at-exhibit-1280w.avif",
        "w": 1280
      },
      {
        "src": "/images/vimeo-poster-life-at-exhibit-1920w.webp",
        "avif": "/images/vimeo-poster-life-at-exhibit-1920w.avif",
        "w": 1920
      }
    ]
  }
};
